### ISSUE TITLE
Build failed.

### ISSUE THREAD

**Issue by SimSonic** [HexogenDev/Hexogen-Standalone#1]
Ни master, ни experimental не собрались...
[#2 @ CI](https://ci.methuselah.ru/job/CyanWool/2/console)

**Comment by BeYkeRYkt** [comment]
Я все еще пишу API, думаю скоро заведется)

**Comment by SimSonic** [comment]
Если что, оно автоматически следит за коммитами (проверка каждый час), если есть новые, пытается сделать сборку. Используется JDK 6 для [API](https://ci.methuselah.ru/job/CyanWool-API/) и JDK 7 для [сервера](https://ci.methuselah.ru/job/CyanWool/) (увидел это в **pom.xml**).
